//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTracker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveIssue
    {
        public int Id { get; set; }
        public int OriginalIssueId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public System.DateTime ArchivedDate { get; set; }
    }
}
